---
- name: Set up the reaper repo
  copy:
    dest: /etc/yum.repos.d/cassandra-reaper.repo
    owner: root
    group: root
    mode: 0644
    content: |
      [bintraybintray-thelastpickle-reaper-rpm]
      name=bintray-thelastpickle-reaper-rpm
      baseurl=https://dl.bintray.com/thelastpickle/reaper-rpm
      gpgcheck=0
      repo_gpgcheck=0
      enabled=1

- name: Install Cassandra Reaper
  package: 
    name:
      - reaper
      - java-1.8.0-openjdk
    state: present  
  
- name: Set up postgres 10 repo
  package:
    name:
      - https://yum.postgresql.org/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    state: present

- name: Install postgres 10
  package:
    name:
      - postgresql10-server
      - postgresql10
      - python-psycopg2
    state: present

- name: Initialise postgres db
  shell: /usr/pgsql-10/bin/postgresql-10-setup initdb

- name: Start postgresql
  service:
    name: postgresql-10
    enabled: true
    state: restarted

- name: Create postgresql db
  postgresql_db:
    name: "{{ reaper_db_name }}"
  become: yes
  become_user: postgres

- name: Create postgresql user
  postgresql_user:
    db: "{{ reaper_db_name }}"
    name: "{{ reaper_db_user }}"
    password: "{{ reaper_db_pass }}"
  become: yes
  become_user: postgres

- name: Set postgres user password
  postgresql_user:
    name: postgres
    password: "{{ postgres_user_pass }}"
  become: yes
  become_user: postgres

- name: Configure pg_hba.conf
  copy:
    dest: /var/lib/pgsql/10/data/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600
    content: |
      # Generated by ansible
      local   all             all                                     md5
      host    all             all             127.0.0.1/32            md5

- name: Restart postgresql
  service:
    name: postgresql-10
    state: restarted

- name: Copy Reaper config file
  copy:
    src: cassandra-reaper-postgres.yaml
    dest: /etc/cassandra-reaper/cassandra-reaper.yaml

- name: Update reaper config
  replace:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    regexp: 'string_reaper_db_name'
    replace: "{{ reaper_db_name }}"

- name: Update reaper config
  replace:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    regexp: 'string_reaper_db_user'
    replace: "{{ reaper_db_user }}"

- name: Update reaper config
  replace:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    regexp: 'string_reaper_db_pass'
    replace: "{{ reaper_db_pass }}"

- name: Update reaper config
  replace:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    regexp: 'string_reaper_jmx_user'
    replace: "{{ reaper_jmx_user }}"

- name: Update reaper config
  replace:
    path: /etc/cassandra-reaper/cassandra-reaper.yaml
    regexp: 'string_reaper_jmx_pass'
    replace: "{{ reaper_jmx_pass }}"

- name: Start Reaper
  service:
    name: cassandra-reaper
    enabled: true
    state: restarted

- name: Open firewall for Reaper UI
  firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
